import { Observable } from 'rxjs';
import { JobCollectionsMap, JobSources, QuarterData } from './job-sources.types';

export const jobCollectionsMap: JobCollectionsMap = {
  gupyDev: {
    name: 'Desenvolvimento Web',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: [
      'desenvolvedor',
      'dev',
      'front',
      'back',
      'full',
      'fullstack',
      'software',
    ],
    initialDailyFetchDate: '19/12/2023',
  },
  gupyMobile: {
    name: 'Mobile',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['mobile', 'android', 'ios'],
    initialDailyFetchDate: '05/02/2024',
  },
  gupyDevops: {
    name: 'DevOps',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['devops', 'sre', 'devsecops', 'cloud'],
    initialDailyFetchDate: '05/02/2024',
  },
  gupyUIUX: {
    name: 'UI/UX',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['ui', 'ux'],
    initialDailyFetchDate: '05/02/2024',
  },
  gupyDados: {
    name: 'Dados',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['data', 'dados'],
    initialDailyFetchDate: '05/02/2024',
  },
  gupyQA: {
    name: 'QA',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['qa', 'teste', 'quality assurance'],
    initialDailyFetchDate: '09/02/2024',
  },
  gupyIA: {
    name: 'IA',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: [
      'ia',
      'ai',
      'machine learning',
      'inteligencia artificial',
      'deep learning',
    ],
    initialDailyFetchDate: '09/02/2024',
  },
  gupyProductManager: {
    name: 'Product Manager',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['product manager'],
    initialDailyFetchDate: '22/02/2024',
  },
  gupyAgileRelated: {
    name: 'Agilista/Scrum Master',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['agilista', 'scrum', 'agile'],
    initialDailyFetchDate: '23/02/2024',
  },
  gupyRecruitment: {
    name: 'Recrutamento',
    icon: 'bx bxs-business',
    source: JobSources.gupy,
    dataByYear: {},
    searchStringKeywords: ['recrutador', 'recruiter', 'recrutamento', 'recursos humanos', 'RH'],
    initialDailyFetchDate: '05/03/2024',
  },
  frontendbr: {
    name: 'frontendbr/vagas',
    icon: 'bx bxl-github',
    source: JobSources.github,
    dataByYear: {},
    searchStringKeywords: ['não se aplica'],
    initialDailyFetchDate: 'Em progresso',
  },
  backendbr: {
    name: 'backend-br/vagas',
    icon: 'bx bxl-github',
    source: JobSources.github,
    dataByYear: {},
    searchStringKeywords: ['não se aplica'],
    initialDailyFetchDate: 'Em progresso',
  },
  soujava: {
    name: 'soujava/vagas-java',
    icon: 'bx bxl-github',
    source: JobSources.github,
    dataByYear: {},
    searchStringKeywords: ['não se aplica'],
    initialDailyFetchDate: 'Em progresso',
  },
  reactBrasil: {
    name: 'react-brasil/vagas',
    icon: 'bx bxl-github',
    source: JobSources.github,
    dataByYear: {},
    searchStringKeywords: ['não se aplica'],
    initialDailyFetchDate: 'Em progresso',
  },
  androidDevBr: {
    name: 'androiddevbr/vagas',
    icon: 'bx bxl-github',
    source: JobSources.github,
    dataByYear: {},
    searchStringKeywords: ['não se aplica'],
    initialDailyFetchDate: 'Em progresso',
  },
  linkedinDev: {
    name: 'Desenvolvimento de software',
    icon: 'bx bxl-linkedin-square',
    source: JobSources.linkedin,
    dataByYear: {},
    searchStringKeywords: ['desenvolvedor'],
    initialDailyFetchDate: '08/02/2024',
  },
  linkedinDevOpsBr: {
    name: 'DevOps (BR)',
    icon: 'bx bxl-linkedin-square',
    source: JobSources.linkedin,
    dataByYear: {},
    searchStringKeywords: ['devops', 'cloud', 'sre'],
    initialDailyFetchDate: '08/07/2025',
  },
};

export const defaultQuarterData: QuarterData = {
  dataSource: new Observable(),
  isCurrentQuarter: false,
  isUpcomingQuarter: false,
  isSelected: false,
  isDownloading: false,
  isLoading: false,
  isLoaded: false,
  hasFailedToLoad: false,
  loadingProgress: 0,
  canTrackDownloadProgress: false,
  downloadingProgress: 0,
};
