export interface Keywords {
  [key: string]: string;
}

export const keywords: Keywords = {
  //FRONTEND
  html: 'HTML',
  css: 'CSS',
  javascript: 'JavaScript',
  js: 'JavaScript',
  typescript: 'TypeScript',
  ts: 'TypeScript',
  react: 'React',
  reactjs: 'React',
  'react.js': 'React',
  angular: 'Angular',
  angularjs: 'AngularJS',
  'vue.js': 'Vue.js',
  vuejs: 'Vue.js',
  bootstrap: 'Bootstrap',
  sass: 'Sass',
  less: 'Less',
  redux: 'Redux',
  webpack: 'Webpack',
  babel: 'Babel',
  'responsive design': 'Responsive Design',
  'restful apis': 'RESTful APIs',
  restful: 'RESTful APIs',
  graphql: 'GraphQL',
  ajax: 'AJAX',
  json: 'JSON',
  xml: 'XML',
  'ui/ux design': 'UI/UX Design',
  'frontend testing': 'Testes',
  stylus: 'Stylus',
  //BACKEND
  kotlin: 'Kotlin',
  'node.js': 'Node.js',
  node: 'Node.js',
  nodejs: 'Node.js',
  'express.js': 'Express',
  express: 'Express',
  java: 'Java',
  'spring boot': 'Spring Boot',
  springboot: 'Spring Boot',
  spring: 'Spring Boot',
  python: 'Python',
  django: 'Django',
  ruby: 'Ruby',
  'ruby on rails': 'Ruby on Rails',
  rails: 'Ruby On Rails',
  php: 'PHP',
  laravel: 'Laravel',
  'asp.net': '.NET',
  '.net': '.NET',
  '.net core': '.NET',
  csharp: 'C#',
  'c#': 'C#',
  go: 'Go',
  golang: 'Go',
  flask: 'Flask',
  fastapi: 'FastAPI',
  'database management': 'Database Management',
  'api development': 'API Development',
  'authentication and authorization': 'Authentication and Authorization',
  oauth: 'OAuth',
  jwt: 'JWT',
  'security best practices': 'Security Best Practices',
  'c++': 'C++',
  C: 'C',
  soap: 'SOAP',
  //DATABASE
  sql: 'SQL',
  nosql: 'NoSQL',
  mongodb: 'MongoDB',
  mysql: 'MySQL',
  postgresql: 'PostgreSQL',
  elasticsearch: 'Elasticsearch',
  //MOBILE
  android: 'Android',
  ios: 'iOS',
  swift: 'Swift',
  ionic: 'Ionic',
  cordova: 'Cordova',
  'apache cordova': 'Cordova',
  //CLOUD
  microservices: 'Microsserviços',
  'micro serviços': 'Microsserviços',
  aws: 'AWS',
  cloudflare: 'Cloudflare',
  gcp: 'GCP',
  'Google Cloud Platform': 'GCP',
  azure: 'Azure',
  'web servers': 'Web Servers',
  nginx: 'Nginx',
  apache: 'Apache',
  //TESTING,
  junit: 'JUnit',
  mockito: 'Mockito',
  teste: 'Testes',
  jest: 'Jest',
  enzyme: 'Enzyme',
  cypress: 'Cypress',
  //MISCELLANEOUS
  git: 'Git',
  github: 'GitHub',
  scrum: 'Scrum',
  gitlab: 'Gitlab',
  'clean code': 'Clean Code',
  'clean architecture': 'Clean Architecture',
  lean: 'Lean',
  kanbam: 'Kanbam',
  salesforce: 'Salesforce',
};
